import dbClient from '../utils/db';
const sha1 = require('sha1');

class UsersController {
  static async postNew (request, response) {
    const { email, password } = request.body;
    if (!email) {
      response.status(400).json({ error: 'Missing email' });
      return;
    }

    if (!password) {
      response.status(400).json({ error: 'Missing password' });
      return;
    }

    const hashedPassword = sha1(password);

    const users = dbClient.db.collection('users');

    const user = await users.findOne({ email });
    if (user) {
      response.status(400).json({ error: 'Already exist' });
      return;
    }
    // return id generated by mongodb
    const { insertedId } = await users.insertOne({
      email,
      password: hashedPassword
    });
    response.status(201).json({ email, id: insertedId });
  }
}

module.exports = UsersController;
