import dbClient from "../utils/db";
const { ObjectId } = require("mongodb");
const sha1 = require("sha1");

class UsersController {
  static async postNew(request, response) {
    // create user with email and password
    // response.status(200).send("ok")
    const { email, password } = request.body;
    if (!email) {
      response.status(400).send("Missing email");
      return;
    }

    if (!password) {
      response.status(400).send("Missing password");
      return;
    }

    const hashedPassword = sha1(password);

    const users = dbClient.db.collection("users");

    const user = await users.findOne({ email });
    if (user) {
      response.status(400).send("Already exist");
      return;
    }
    // return id generated by mongodb
    const { insertedId } = await users.insertOne({ email, hashedPassword });
    response.status(201).json({ email, id: insertedId });
  }
}

module.exports = UsersController;
